# Generated by Django 3.1.7 on 2021-09-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210902_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, help_text="Sotilgan bo'lsa belgilang!!!", verbose_name='Sotildi'),
        ),
    ]
