# Generated by Django 3.1.7 on 2021-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210914_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='income',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Daromad'),
        ),
    ]
