# Generated by Django 3.1.7 on 2021-09-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Mahsulot soni'),
        ),
    ]
